### ISSUE TITLE
Can't properly see the unicodes

### ISSUE THREAD

**Issue by MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM** [AnonCatalyst/Ominis-Osint#3]
I'm on Windows 10 21H2 with no custom fonts at all and the unicodes aren't supported on my OS i think 
![image](https://github.com/AnonCatalyst/Ominis-Osint/assets/103538486/da9d0ae2-3298-4c69-be79-34237d7413d4)

**Comment by AnonCatalyst** [comment]
Hey we recently removed the unicodes. Please clone the repository again to see what's new.

**Comment by AnonCatalyst** [comment]
Please clone the repository again, I recently removed the unicode.
